const TOKEN = {
  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_SECRET,
  ACCESS_TOKEN_COOKIE_NAME: 'access_token',
  REFRESH_TOKEN_COOKIE_NAME: 'refresh_token',
  ACCESS_TOKEN_EXPIRES_IN: 1000 * 60 * 15, // 15분
  REFRESH_TOKEN_EXPIRES_IN: 7 * 24 * 60 * 60 * 1000, // 7일
};

export default TOKEN;
